### ISSUE TITLE
可以直接14393起步。以前的可以不兼容了

### ISSUE THREAD

**Issue by RubickMischief** [M2Team/Nagisa#2]
RT

**Comment by vbfool** [comment]
14393起步唯一的好处也就是单进程后台而已了吧，HTTP和HTTPS的下载，作者的意向并不是使用BITS，是通过Socket自己来。

**Comment by MouriNaruto** [comment]
刚刚看见，于是我说明下暂时不14393的理由

1.观望C++/WinRT项目的发展；想等这个项目成熟的时候连最低系统要求一起升。因为C++/WinRT可以让我完全用标准C++语法编写UWP而且二进制大小比C++/CX小不少效率也高不少
2.照顾下入WP坑的人。虽然WP第一个正式版是10586；但这个版本既不是第一个Windows 10版本，又没有对应的Server正式版本；看起来并不像传统意义的RTM；所以没有升级到10586的兴趣
3.Nagisa所需要的功能，10240 SDK应该足够招架了

**Comment by RubickMischief** [comment]
没毛病。 
如果不需要写很多兼容代码的话，当然支持的越多越好啦。
