### ISSUE TITLE
终于看到勇士了

### ISSUE THREAD

**Issue by liyk123** [M2Team/Nagisa#8]
去年的时候本人用C++/CX做过UWP的IP Camera的监控应用，不过是给公司做的(虽然后来公司弃用了)，现在主要做Win32开发，隔了这么长的时间，终于看到了用C++/CX开发UWP的人，加油吧！另外建议界面的部分用C#+XAML做，基础构件使用C++/CX，这样比较灵活，微软的开源项目也是这样做的，虽然界面部分他是给出了多语言示例，但是通过比较还是C#在这方面更具有优势。

**Comment by MouriNaruto** [comment]
感谢支持

我完全使用C++/CX主要有以下原因：

1. 因为.Net Native生成的二进制体积增长速度超出了我的忍受范围（与C++/CX编译的体积相差几十倍）
2. 我习惯先在UI部分写实现以方便调试，稳定后再放到基础构件里面；由于我习惯使用Win32 API，于是C++比较适合我
3. 现阶段.Net Native不支持ARM64
4. UWP的框架（Windows Runtime）是用C++写的，用.Net调用UWP的接口有比较大的开销（微软都建议用.Net开发UWP的时候尽量使用.Net的API而不是Windows Runtime的API）

不知道你怎么看
